url: https://isoauditguru.github.io/
baseurl:

title: IAG
email: guru@isoauditguru.com
description: "Improve Adapt Glitter"

member:
  name: Balaji Rajaraman
  pic: 42
  position: Boss
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/rajaramanbalaji/
  description: |
    ISO Audit Guru is promoted by Balaji Rajaraman, a Printing Technologist, Lead Auditor &amp; Consultant in Quality,
    Environment, Occupational Health &amp; Safety, Energy and Information Security Management Systems. He has over 750 man-days of audit and about 400 days of training experience, he has worked alongside reputed clients
    in Manufacturing, Service, IT/ITES, Finance and Education sectors.  

social:
  - title: linkedin
    url: https://www.linkedin.com/in/rajaramanbalaji/

markdown: kramdown
permalink: pretty

collections:
  testimonials:
    output: true
