url: https://isoauditguru.github.io/
baseurl:

title: IAG
email: sanjayms0111@gmail.com
description: "IAG is this that."

member:
  name: Balaji Rajaraman
  pic: 42
  position: Boss
  social:
    - title: linkedin
      url: https://linkedin.com/in/
  description: |
    ISO Audit Guru is promoted by Balaji Rajaraman, a Printing Technologist and a Lead Auditor &amp; Consultant in Quality,
    Environment, Occupational Health &amp; Safety, Energy and Information Security. He has over 750 man-
    days of audit and about 400 days of training experience, he has worked alongside reputed clients
    from Manufacturing, IT/ITES, Finance and Education sectors.  

social:
  - title: linkedin
    url: https://linkedin.com/in/

markdown: kramdown
permalink: pretty

collections:
  testimonials:
    output: true
  slides:
    output: true

defaults:
  -
    scope:
      path: "_slides"  #__
    values:
      layout: "iframe"
